routes/web.php
<?php

use App\Http\Controllers\TasksController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth'])->group(function(){

    Route::middleware(['role:leader'])->group(function(){
        Route::name('leader.')->group(function(){
            Route::get('/leader', [UserController::class, 'leader'])->name('index');
            Route::get('/leader/members', [UserController::class, 'leaderMembers'])->name('members');
            Route::resource('/leader/tasks', TasksController::class);
        });
    });

    Route::middleware(['role:member'])->group(function(){
        Route::name('member.')->group(function(){
            Route::get('/member', [UserController::class, 'member'])->name('index');
            Route::get('/member/task/{task}', [TasksController::class, 'memberShow'])->name('tasks.show');
            Route::get('/member/tasks', [TasksController::class, 'memberTasks'])->name('tasks');
            Route::get('/member/assigned-tasks', [TasksController::class, 'memberAssignedTasks'])->name('tasks.assigned');
            Route::get('/member/resolved-tasks', [TasksController::class, 'memberResolvedTasks'])->name('tasks.resolved');
            Route::get('/member/unresolved-tasks', [TasksController::class, 'memberUnresolvedTasks'])->name('tasks.unresolved');
            Route::put('/member/tasks/{task}/resolved', [TasksController::class, 'markAsResolved']);
            Route::put('/member/tasks/{task}/unresolved', [TasksController::class, 'markAsUnresolved']);
        });
    });

    Route::get('/download/{task}', [TasksController::class, 'download'])->name('task.download');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * ACCESSORS
     */

    public function getAvatarAttribute() {
        $size = 45;
        $name = $this->name;
        $length = 2;
        return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}&length={$length}&background=random";
    }

    /**
     * RELATIONSHIP METHODS
     */

    public function team()
    {
        if($this->role == 'leader'){
            return $this->hasOne(Team::class, 'leader_id');
        }
        else if($this->role == 'member'){
            return $this->belongsTo(Team::class);
        }

    }

    public function tasks()
    {
        if($this->role == 'leader') {
            return $this->hasMany(Task::class, 'leader_id');
        }
        else if($this->role == 'member') {
            return $this->hasMany(Task::class, 'member_id');
        }
    }
}

resources/views/leader/_sidebar.blade.php
@section('sidebar')
    <ul class="list-group">
        <li class="list-group-item"><a href="{{ route('leader.members') }}">Team Members</a></li>
        <li class="list-group-item"><a href="{{ route('leader.tasks.index') }}">Tasks</a></li>
    </ul>
@endsection

resources/views/leader/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header"><h3>Create a Task</h3></div>
                    <div class="card-body">
                        <form action="{{ route('leader.tasks.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label for="title">Title</label>
                                <input type="text" id="title" name="title" placeholder="Enter Title" value = "{{ old('title') }}"
                                    class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}">
                                @error('title')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="body">Body</label>
                                <input id="body" type="hidden" name="body" value="{{ old('body') }}">
                                <trix-editor input="body" placeholder="Enter body"></trix-editor>
                                @error('body')
                                    <div class="text-danger">{{ $message }}</div>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="member_id">Member</label>
                                <select name="member_id" id="member_id" class="form-control select2">
                                    <option value="0" selected disabled>Select Member</option>
                                    @foreach ($members as $member)
                                        <option value="{{ $member->id }}"
                                            @if($member->id == old('member_id')) selected @endif>{{ $member->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <div class="custom-file">
                                    <label for="attachment" class="custom-file-label">Select Attachment</label>
                                    <input type="file" name="attachment" id="attachment" class="custom-file-input @error('attachment') is-invalid @enderror">
                                    @error('attachment')
                                        <p class="text-danger">{{ $message }}</p>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-success">Create Task!</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.1/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.select2').select2();
        });
        $('input[type="file"]').change(function(e){
        var fileName = e.target.files[0].name;
        $('.custom-file-label').html(fileName);
    });
    </script>

@endsection

@section('styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endsection

resources/views/leader/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="card">
        <div class="card-header">Edit Post</div>

        <div class="card-body">
            <form action="{{ route('leader.tasks.update', $task->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" id="title" name="title" placeholder="Enter Title" value = "{{ old('title', $task->title) }}"
                        class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}">
                    @error('title')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="body">Body</label>
                    <input id="body" type="hidden" name="body" value="{{ old('body', $task->body) }}">
                    <trix-editor input="body" placeholder="Enter body" value="{{ old('body', $task->body) }}"></trix-editor>
                    @error('body')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="member_id">Member</label>
                    <select name="member_id" id="member_id" class="form-control select2">
                        <option value="0" selected disabled>Select Member</option>
                        @foreach ($members as $member)
                            <option value="{{ $member->id }}"
                                @if($member->id == old('member_id', $task->member_id)) selected @endif>{{ $member->name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <div class="custom-file">
                        <label for="attachment" class="custom-file-label">Select Attachment</label>
                        <input type="file" name="attachment" id="attachment" class="custom-file-input @error('attachment') is-invalid @enderror">
                        @error('attachment')
                            <p class="text-danger">{{ $message }}</p>
                        @enderror
                    </div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-outline-success">Edit Task</button>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.select2').select2();
        });
    </script>
@endsection

@section('styles')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.css">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
@endsection

resources/views/leader/index.blade.php
@extends('layouts.app')

@include('leader._sidebar')

@section('main-content')
    <div class="card">
        <div class="card-body">
            <p>Welcome to leader dashboard!</p>
        </div>
    </div>
@endsection

resources/views/leader/members.blade.php
@extends('layouts.app')

@include('leader._sidebar')

@section('main-content')
    <div class="row">
        @foreach ($members as $member)
            <div class="col-md-4 mb-4">
                <div class="card h-100 shadow">
                    <div class="card-body">
                       <div class="media">
                           <img src="{{ $member->avatar }}" alt="User Profile" class="mr-3">
                           <div class="media-body">
                                <h5 class="card-title">{{ $member->name }}</h5>
                                <p class="card-text mb-0">Tasks Assigned: {{ $member->tasks()->where('status', 'assigned')->count() }}</p>
                                <p class="card-text mb-0">Tasks Resolved: {{ $member->tasks()->where('status', 'resolved')->count() }}</p>
                                <p class="card-text">Tasks Unresolved: {{ $member->tasks()->where('status', 'unresolved')->count() }}</p>
                           </div>
                       </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/leader/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-md-4">
                            <img src="{{ $task->member->avatar }}" alt="" class="img-fluid">
                        </div>
                        <div class="col-md-8">
                            <h2>{{ $task->title }}</h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                {!! $task->body !!}
                <p><span class="text-bold"></p>
                <p><span class="font-weight-bold">Status: </span> <span class="{{ $task->textColor }}">{{ Str::ucfirst($task->status) }}</span></p>
                @if ($task->hasAttachment)
                        <p>
                            <a href="{{ route('task.download', $task->id) }}" class="btn btn-outline-secondary">
                                Download Attachment <i class="fa fa-download"></i>
                            </a>
                        </p>
                @endif
                <p class="text-right"><span class="font-weight-bold">Assigned To:</span> {{ $task->member->name }}</p>
            </div>
        </div>
    </div>
@endsection

resources/views/leader/tasks.blade.php
@extends('layouts.app')

@include('leader._sidebar')

@section('main-content')
    <div class="row">
        <div class="col-md-12">
            <div class="d-flex justify-content-end mb-3">
                <a href="{{ route('leader.tasks.create') }}" class="btn btn-outline-primary">New Task <i class="fa fa-plus"></i></a>
            </div>
        </div>
        @foreach ($tasks as $task)
            <div class="col-md-4 mb-4">
                <div class="card h-100 shadow">
                    <div class="card-body">
                        <div class="row h-25">
                            <div class="col-md-3 align-self-center p-2">
                                <img src="{{ $task->member->avatar }}" alt="" class="w-100 rounded align-self-center my-auto">
                            </div>
                            <div class="col-md-9 mb-1">
                                <h6 class="card-title align-self-center mb-0">{{ $task->title }}</h6>
                            </div>
                        </div>
                        <div class="d-flex align-items-end h-75">
                            <div class="row">
                                <div class="col-md-12">
                                    <p class="{{ $task->textColor }} mb-0">{{ Str::ucfirst($task->status) }}</p>
                                    <p class="mb-2"><span class="font-weight-bold">Assigned to:</span> {{ $task->member->name }}</p>
                                    <a href="{{ route('leader.tasks.show', $task->id) }}" class="btn btn-outline-primary btn-sm ml-auto"><i class="fa fa-eye"></i></a>
                                    <a href="{{ route('leader.tasks.edit', $task->id) }}" class="btn btn-outline-secondary btn-sm ml-auto"><i class="fa fa-pencil"></i></a>
                                    <a href="{{ route('leader.tasks.destroy', $task->id) }}"
                                        class="btn btn-outline-danger btn-sm ml-auto" onclick="displayModalForm({{$task}})"
                                        data-toggle="modal" data-target="#deleteModal">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Delete Task</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" method="POST" id="deleteForm">
                    @csrf
                    @method('DELETE');
                    <div class="modal-body">
                        <p>Are you sure you want to delete the task?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-danger">Delete Task</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

@section('scripts')
    <script type="text/javascript">
        function displayModalForm($task){
            var url = '/leader/tasks/' + $task.id;
            $('#deleteForm').attr('action', url);
        }
    </script>
@endsection