routes/web.php
<?php

use App\Http\Controllers\TasksController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['auth'])->group(function(){

    Route::middleware(['role:leader'])->group(function(){
        Route::name('leader.')->group(function(){
            Route::get('/leader', [UserController::class, 'leader'])->name('index');
            Route::get('/leader/members', [UserController::class, 'leaderMembers'])->name('members');
            Route::resource('/leader/tasks', TasksController::class);
        });
    });

    Route::middleware(['role:member'])->group(function(){
        Route::name('member.')->group(function(){
            Route::get('/member', [UserController::class, 'member'])->name('index');
            Route::get('/member/task/{task}', [TasksController::class, 'memberShow'])->name('tasks.show');
            Route::get('/member/tasks', [TasksController::class, 'memberTasks'])->name('tasks');
            Route::get('/member/assigned-tasks', [TasksController::class, 'memberAssignedTasks'])->name('tasks.assigned');
            Route::get('/member/resolved-tasks', [TasksController::class, 'memberResolvedTasks'])->name('tasks.resolved');
            Route::get('/member/unresolved-tasks', [TasksController::class, 'memberUnresolvedTasks'])->name('tasks.unresolved');
            Route::put('/member/tasks/{task}/resolved', [TasksController::class, 'markAsResolved']);
            Route::put('/member/tasks/{task}/unresolved', [TasksController::class, 'markAsUnresolved']);
        });
    });

    Route::get('/download/{task}', [TasksController::class, 'download'])->name('task.download');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Auth;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * ACCESSORS
     */

    public function getAvatarAttribute() {
        $size = 45;
        $name = $this->name;
        $length = 2;
        return "https://ui-avatars.com/api/?name={$name}&rounded=true&size={$size}&length={$length}&background=random";
    }

    /**
     * RELATIONSHIP METHODS
     */

    public function team()
    {
        if($this->role == 'leader'){
            return $this->hasOne(Team::class, 'leader_id');
        }
        else if($this->role == 'member'){
            return $this->belongsTo(Team::class);
        }

    }

    public function tasks()
    {
        if($this->role == 'leader') {
            return $this->hasMany(Task::class, 'leader_id');
        }
        else if($this->role == 'member') {
            return $this->hasMany(Task::class, 'member_id');
        }
    }
}

resources/views/member/_sidebar.blade.php
@section('sidebar')
    <ul class="list-group">
        <li class="list-group-item"><a href="{{ route('member.tasks') }}">All Tasks</a></li>
        <li class="list-group-item"><a href="{{ route('member.tasks.assigned') }}">Assigned Tasks</a></li>
        <li class="list-group-item"><a href="{{ route('member.tasks.resolved') }}">Resolved Tasks</a></li>
        <li class="list-group-item"><a href="{{ route('member.tasks.unresolved') }}">Unresolved Tasks</a></li>
    </ul>
@endsection

resources/views/member/assignedTasks.blade.php
@extends('layouts.app')

@include('member._sidebar')

@section('main-content')
    <div class="row">
        @foreach ($tasks as $task)
            <div class="col-md-4 mb-4">
                <div class="card h-100 shadow">
                    <div class="card-body">
                        <div class="row h-25">
                            <div class="col-md-3 align-self-center p-2">
                                <img src="{{ $task->leader->avatar }}" alt="" class="w-100 rounded align-self-center my-auto">
                            </div>
                            <div class="col-md-9 mb-1">
                                <h6 class="card-title align-self-center mb-0">{{ $task->title }}</h6>
                            </div>
                        </div>
                        <div class="d-flex align-items-end h-75">
                            <div class="row">
                                <div class="col-md-12">
                                    <p class="{{ $task->textColor }} mb-0">{{ Str::ucfirst($task->status) }}</p>
                                    <p class="mb-2"><span class="font-weight-bold">Assigned by:</span> {{ $task->leader->name }}</p>
                                    <a href="{{ route('member.tasks.show', $task->id) }}" class="btn btn-outline-primary btn-sm ml-auto"><i class="fa fa-eye"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/member/index.blade.php
@extends('layouts.app')

@include('member._sidebar')

@section('main-content')
    <div class="card">
        <div class="card-body">
            <p>Welcome to member dashboard!</p>
        </div>
    </div>
@endsection

resources/views/member/resolvedTasks.blade.php
@extends('layouts.app')

@include('member._sidebar')

@section('main-content')
    <div class="row">
        @foreach ($tasks as $task)
            <div class="col-md-4 mb-4">
                <div class="card h-100 shadow">
                    <div class="card-body">
                        <div class="row h-25">
                            <div class="col-md-3 align-self-center p-2">
                                <img src="{{ $task->leader->avatar }}" alt="" class="w-100 rounded align-self-center my-auto">
                            </div>
                            <div class="col-md-9 mb-1">
                                <h6 class="card-title align-self-center mb-0">{{ $task->title }}</h6>
                            </div>
                        </div>
                        <div class="d-flex align-items-end h-75">
                            <div class="row">
                                <div class="col-md-12">
                                    <p class="{{ $task->textColor }} mb-0">{{ Str::ucfirst($task->status) }}</p>
                                    <p class="mb-2"><span class="font-weight-bold">Assigned by:</span> {{ $task->leader->name }}</p>
                                    <a href="{{ route('member.tasks.show', $task->id) }}" class="btn btn-outline-primary btn-sm ml-auto"><i class="fa fa-eye"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/member/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-9">
            <div class="card shadow-sm">
                <div class="card-header">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-4">
                                <img src="{{ $task->member->avatar }}" alt="" class="img-fluid">
                            </div>
                            <div class="col-md-8">
                                <h2>{{ $task->title }}</h2>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    {!! $task->body !!}
                    <p><span class="text-bold"></p>
                    <p><span class="font-weight-bold">Status: </span> <span class="{{ $task->textColor }}">{{ Str::ucfirst($task->status) }}</span></p>
                    @if ($task->hasAttachment)
                            <p>
                                <a href="{{ route('task.download', $task->id) }}" class="btn btn-outline-secondary">
                                    Download Attachment <i class="fa fa-download"></i>
                                </a>
                            </p>
                    @endif
                    <p class="text-right"><span class="font-weight-bold">Assigned By:</span> {{ $task->leader->name }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card shadow">
                <div class="card-header">
                    <h5 class="card-title">Task action</h5>
                </div>
                <div class="card-body">
                    @if ($task->status === 'assigned')
                        <p>
                            <a href="#" class="btn btn-block btn-outline-success btn-sm" onclick="displayResolvedForm({{$task}})"
                            data-toggle="modal" data-target="#resolvedModal">
                            Mark as Resolved <i class="fa fa-check"></i></a>
                        </p>
                        <p>
                            <a href="#" class="btn btn-block btn-outline-danger btn-sm"
                            onclick="displayUnresolvedForm({{$task}})"
                            data-toggle="modal" data-target="#unresolvedModal">
                                Mark as Unresolved <i class="fa fa-close"></i></a>
                        </p>
                    @else
                        <p class="{{ $task->textColor }} font-weight-bold">Task {{ $task->status }}</p>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="resolvedModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Mark as Resolved</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" method="POST" id="resolvedForm">
                    @csrf
                    @method('PUT');
                    <div class="modal-body">
                        <p>Are you sure you want to mark as Resolved?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">No</button>
                        <button type="submit" class="btn btn-outline-success">Mark as Resolved</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="modal fade" id="unresolvedModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Mark as Unresolved</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form action="" method="POST" id="unresolvedForm">
                    @csrf
                    @method('PUT');
                    <div class="modal-body">
                        <p>Are you sure you want to mark as unresolved?</p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">No</button>
                        <button type="submit" class="btn btn-outline-danger">Mark as Unresolved</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script type="text/javascript">
        function displayResolvedForm($task){
            var url = '/member/tasks/' + $task.id + '/resolved';
            $('#resolvedForm').attr('action', url);
        }
        function displayUnresolvedForm($task){
            var url = '/member/tasks/' + $task.id + '/unresolved';
            $('#unresolvedForm').attr('action', url);
        }
    </script>
@endsection

resources/views/member/tasks.blade.php
@extends('layouts.app')

@include('member._sidebar')

@section('main-content')
    <div class="row">
        @foreach ($tasks as $task)
            <div class="col-md-4 mb-4">
                <div class="card h-100 shadow">
                    <div class="card-body">
                        <div class="row h-25">
                            <div class="col-md-3 align-self-center p-2">
                                <img src="{{ $task->leader->avatar }}" alt="" class="w-100 rounded align-self-center my-auto">
                            </div>
                            <div class="col-md-9 mb-1">
                                <h6 class="card-title align-self-center mb-0">{{ $task->title }}</h6>
                            </div>
                        </div>
                        <div class="d-flex align-items-end h-75">
                            <div class="row">
                                <div class="col-md-12">
                                    <p class="{{ $task->textColor }} mb-0">{{ Str::ucfirst($task->status) }}</p>
                                    <p class="mb-2"><span class="font-weight-bold">Assigned by:</span> {{ $task->leader->name }}</p>
                                    <a href="{{ route('member.tasks.show', $task->id) }}" class="btn btn-outline-primary btn-sm ml-auto"><i class="fa fa-eye"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

resources/views/member/unresolvedTasks.blade.php
@extends('layouts.app')

@include('member._sidebar')

@section('main-content')
    <div class="row">
        @foreach ($tasks as $task)
            <div class="col-md-4 mb-4">
                <div class="card h-100 shadow">
                    <div class="card-body">
                        <div class="row h-25">
                            <div class="col-md-3 align-self-center p-2">
                                <img src="{{ $task->leader->avatar }}" alt="" class="w-100 rounded align-self-center my-auto">
                            </div>
                            <div class="col-md-9 mb-1">
                                <h6 class="card-title align-self-center mb-0">{{ $task->title }}</h6>
                            </div>
                        </div>
                        <div class="d-flex align-items-end h-75">
                            <div class="row">
                                <div class="col-md-12">
                                    <p class="{{ $task->textColor }} mb-0">{{ Str::ucfirst($task->status) }}</p>
                                    <p class="mb-2"><span class="font-weight-bold">Assigned by:</span> {{ $task->leader->name }}</p>
                                    <a href="{{ route('member.tasks.show', $task->id) }}" class="btn btn-outline-primary btn-sm ml-auto"><i class="fa fa-eye"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection